---
- name: Execute multiple playbooks with delay
  hosts: localhost  # This runs on the control node (local machine)
  vars:
      git_repo: https://github.com/username/repository.git  # Replace with your Git repository URL
      git_dest: /home/ubuntu/project-zero/  # Destination directory
  tasks:

    - name: Clone repository from Git
      ansible.builtin.git:
        repo: "{{ git_repo }}"  # Replace with your Git repository URL
        dest: "{{ git_dest }}"  # Destination path on the client machine
        version: main  # Branch, tag, or commit to check out (default is 'HEAD')
        force: yes  # Force the clone if the destination already exists

    - name: Set up and configure AWS CLI
      ansible.builtin.command:
        cmd: ansible-playbook /home/ubuntu/project-zero/ansible/2-aws-setup-configure.yaml
      register: playbook1_result

    - name: Wait for 10 seconds after first playbook
      ansible.builtin.pause:
        seconds: 10

    - name: install Terraform
      ansible.builtin.command:
        cmd: ansible-playbook /home/ubuntu/project-zero/ansible/3-terraform-setup.yaml
      register: playbook2_result

