---
- name: Install Terraform and AWS CLI
  hosts: localhost
  become: true
  vars:
    aws_installation_url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    aws_access_key: "AKIA5FTZFH56B6DFDYOS"
    aws_secret_key: "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"
    aws_default_region: "us-east-1"
    output_format: "json"
  tasks:
    - name: Ensure required packages are installed
      package:
        name:
          - unzip
          - curl
        state: present

    - name: Download AWS CLI installer
      get_url:
        url: " {{aws_installation_url}} "
        dest: /tmp/awscliv2.zip

    - name: Extract AWS CLI installer
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp/
        remote_src: yes

    ##THIS TASK WILL CAUSE AN ERROR IF AWS HAS INSTALLE
    #BEST PRACTICE IS TO CHECK IF AWS INSTALLED BEFORE INSTALLING IT
    # - name: Install AWS CLI
    #   command: /tmp/aws/install

    - name: Check if AWS CLI is installed
      shell: |
        aws --version
      register: aws_cli_check
      failed_when: false
      changed_when: false

    - name: Install or Update AWS CLI if not installed
      shell: |
        ./aws/install --update
      args:
        chdir: /tmp
      when: aws_cli_check.rc != 0
      become: true

    - name: Verify AWS CLI installation
      command: aws --version
      register: aws_output
      changed_when: false

    - name: Show AWS CLI version
      debug:
        msg: "{{ aws_output.stdout }}"

    - name: Configure AWS CLI using `aws configure`
      shell: |
        echo "{{aws_access_key}}\n{{aws_secret_key}}\n{{aws_default_region}}\n{{output_format}}" | aws configure
      become_user: ubuntu # to run this command as ubuntu user not as root user
