---
- name: Install ArgoCD CLI
  hosts: master
  become: yes
  tasks:
    - name: Download the ArgoCD CLI binary
      ansible.builtin.get_url:
        url: "https://github.com/argoproj/argo-cd/releases/download/v2.13.2/argocd-linux-amd64"
        dest: "/usr/local/bin/argocd"
        mode: '0755'

    - name: Verify ArgoCD CLI installation
      ansible.builtin.command: argocd version
      register: argocd_version_output
      failed_when: "'Version' not in argocd_version_output.stdout"

    - name: Display installed ArgoCD CLI version
      ansible.builtin.debug:
        msg: "{{ argocd_version_output.stdout }}"
