- name: Deploy ArgoCD Application using Ansible
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Fetch ArgoCD master IP
      ansible.builtin.shell:
        cmd: kubectl get svc argo-cd-server -n argocd -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
        register: argo_master_ip
      failed_when: false
      changed_when: false

    - name: Get ArgoCD NodePort
      ansible.builtin.shell:
        cmd: kubectl get svc argocd-server -n argocd -o jsonpath='{.spec.ports[0].nodePort}'
        register: argo_node_port
      failed_when: false
      changed_when: false

    - name: Set ArgoCD URL
      set_fact:
        argo_cd_url: "https://{{ argo_master_ip.stdout }}:{{ argo_node_port.stdout }}"

    - name: Login to ArgoCD
      ansible.builtin.shell:
        cmd: argocd login {{ argo_cd_url }} --username your-username --password "{{ lookup('env', 'ARGOCD_PASSWORD') }}"
        register: argo_login_result
      changed_when: argo_login_result is changed

    - name: Create ArgoCD application
      ansible.builtin.shell:
        cmd: |
          argocd app create example-app \
            --repo https://github.com/your-username/your-repo.git \
            --path ./path/to/your/manifest \
            --dest-server https://kubernetes.default.svc \
            --dest-namespace default
        register: argo_create_result

    - name: Sync ArgoCD application
      ansible.builtin.shell:
        cmd: argocd app sync example-app
        when: argo_create_result is success
