# sudo apt update && sudo apt install -y python3-pip
# sudo python3.12 -m pip install kubernetes --break-system-packages



# - name: Patch Kubernetes Service
#   hosts: master  # Assuming you're running Ansible on the Kubernetes master
#   tasks:
#   - name: Patch service with type LoadBalancer
#     k8s:
#       state: present
#       kind: Service
#       namespace: argocd
#       name: argocd-server
#       merge_type: merge
#       resource_definition:
#         metadata:
#           annotations:
#             service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
#             service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
#             service.beta.kubernetes.io/aws-load-balancer-internal: "false"
#         spec:
#           type: LoadBalancer





- name: Recreate the ArgoCD server service
  hosts: master
  tasks:
    - name: Delete existing service
      k8s:
        state: absent
        kind: Service
        namespace: argocd
        name: argocd-server

    - name: Create a new service with LoadBalancer type
      k8s:
        state: present
        kind: Service
        namespace: argocd
        resource_definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: argocd-server
            namespace: argocd
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
              service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
              service.beta.kubernetes.io/aws-load-balancer-internal: "false"
              
          spec:
            type: LoadBalancer
            ports:
              - name: http
                port: 80
                protocol: TCP
                targetPort: 8080
              - name: https
                port: 443
                protocol: TCP
                targetPort: 8080
            selector:
              app.kubernetes.io/name: argocd-server

