---
- name: Clone Git repository
  hosts: localhost
  become: yes
  vars:
      terraform_binary_url: https://releases.hashicorp.com/terraform/1.10.3/terraform_1.10.3_linux_amd64.zip  # Replace with your Terraform binary URL
  tasks:
    - name: Ensure required packages are installed
      package:
        name:
          - unzip
          - curl
        state: present

    - name: Download Terraform binary
      get_url:
        url: "{{ terraform_binary_url }}"
        dest: /tmp/terraform.zip

    - name: Extract Terraform binary
      unarchive:
        src: /tmp/terraform.zip
        dest: /usr/local/bin/
        remote_src: yes

    - name: Verify Terraform installation
      command: terraform --version
      register: terraform_output
      changed_when: false

    - name: Show Terraform version
      debug:
        msg: "{{ terraform_output.stdout }}"