---
- name: Provision infrastructure using Terraform
  hosts: localhost
  vars:
      terraform_dir_code: "/home/ubuntu/project-zero/terraform"  # Destination directory to Terraform code
  tasks:

    - name: Run terraform init
      ansible.builtin.shell: terraform init
      args:
        chdir: "{{terraform_dir_code}}"

    - name: Run terraform apply
      ansible.builtin.shell: terraform apply -auto-approve
      args:
        chdir: "{{terraform_dir_code}}"

    - name: Run terraform output
      ansible.builtin.command: terraform output -json
      args:
        chdir: "{{terraform_dir_code}}"
      register: terraform_output

    - name: Display Terraform Outputs
      ansible.builtin.debug:
        msg: "{{ terraform_output.stdout | from_json }}"