---
- name: Copy file to client
  hosts: all
  become: yes
  tasks:
    - name: Copy file from host to client
      ansible.builtin.copy:
        src: /home/ubuntu/project-zero/ansible/config.toml # Path to the file on the control node
        dest: /etc/containerd/  # Destination path on the managed node
        owner: root                # Optional: Set the file owner
        group: root                # Optional: Set the file group
        mode: '0644'               # Optional: Set the file permissions
    - name: Restart containerd service
      service:
        name: containerd
        state: restarted