---
- name: Configure Kubernetes Master Node
  hosts: workers
  become: yes
  tasks:
    - name: Installing kubernetes package using pip
      shell: 
        apt update && sudo apt install -y python3-pip
        python3.12 -m pip install kubernetes --break-system-packages
    - name: Retrieve join command from master
      shell: kubeadm token create --print-join-command
    - name: Set the hostname dynamically
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
    - name: Retrieve join command from master
      shell: kubeadm token create --print-join-command
      register: join_command
      delegate_to: master

    - name: Join the Kubernetes cluster
      shell: "{{ join_command.stdout }}"
