- name: Save variables to a YAML file
  hosts: localhost
  vars:
    terraform_dir_code: "/home/ubuntu/project-zero/terraform"
    output_file: "/home/ubuntu/project-zero/ansible/terraform_outputs.yaml"
  tasks:
    - name: Fetch Subnet ID created using Terraform
      command: terraform output -json subnet_id
      register: subnet_id
      args:
        chdir: "{{ terraform_dir_code }}"

    - name: Fetch EC2 Instance IDs
      command: terraform output -json ec2_ids
      register: ec2_instance_ids
      args:
        chdir: "{{ terraform_dir_code }}"

    - name: Fetch EC2 Instance Public IPs
      command: terraform output -json ec2_public_ips
      register: ec2_public_ips
      args:
        chdir: "{{ terraform_dir_code }}"

    - name: Fetch VPC ID created using Terraform
      command: terraform output -json vpc_id
      register: vpc_id
      args:
        chdir: "{{ terraform_dir_code }}"

    - name: Save variables
      copy:
        content: |
          subnet_id: "{{ subnet_id.stdout | from_json }}"
          ec2_instance_ids:
          {% for ec2_id in ec2_instance_ids.stdout | from_json %}
            - {{ ec2_id }}
          {% endfor %}
          ec2_instance_ips:
          {% for ec2_ip in ec2_public_ips.stdout | from_json %}
            - {{ ec2_ip }}
          {% endfor %}
          vpc_id: "{{ vpc_id.stdout | from_json }}"
        dest: "{{ output_file }}"