---
- name: Configure Kubernetes Master Node
  hosts: workers
  become: yes
  tasks:
    - name: Set the hostname dynamically
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
    - name: Retrieve join command from master
      shell: kubeadm token create --print-join-command
      register: join_command
      delegate_to: master

    - name: Join the Kubernetes cluster
      shell: "{{ join_command.stdout }}"
